import type { ResortCameraGroup } from "./types";

export const FALLBACK_RESORTS: ResortCameraGroup[] = [
  {
    code: "WELLI_HILLI",
    name: "웰리힐리파크",
    regionName: "강원 횡성",
    displayOrder: 1,
    cameras: [
      {
        code: "CAM_01",
        name: "알파 슬로프",
        sourceType: "HLS",
        sourceUrl: "https://live.wellihillipark.com/wellihillipark/_definst_/cam02.stream/playlist.m3u8",
        externalPageUrl: "https://m.wellihillipark.com/customer/webcam",
        displayOrder: 1,
      },
      {
        code: "CAM_02",
        name: "베이스 전경",
        sourceType: "HLS",
        sourceUrl: "https://live.wellihillipark.com/wellihillipark/_definst_/cam03.stream/playlist.m3u8",
        externalPageUrl: "https://m.wellihillipark.com/customer/webcam",
        displayOrder: 2,
      },
      {
        code: "CAM_03",
        name: "슬로프 광장",
        sourceType: "HLS",
        sourceUrl: "https://live.wellihillipark.com/wellihillipark/_definst_/cam04.stream/playlist.m3u8",
        externalPageUrl: "https://m.wellihillipark.com/customer/webcam",
        displayOrder: 3,
      },
      {
        code: "CAM_04",
        name: "정상 광장",
        sourceType: "HLS",
        sourceUrl: "https://live.wellihillipark.com/wellihillipark/_definst_/cam05.stream/playlist.m3u8",
        externalPageUrl: "https://m.wellihillipark.com/customer/webcam",
        displayOrder: 4,
      },
      {
        code: "CAM_05",
        name: "슬로프 전경",
        sourceType: "HLS",
        sourceUrl: "https://live.wellihillipark.com/wellihillipark/_definst_/cam06.stream/playlist.m3u8",
        externalPageUrl: "https://m.wellihillipark.com/customer/webcam",
        displayOrder: 5,
      },
      {
        code: "CAM_06",
        name: "워터플래닛 방면",
        sourceType: "HLS",
        sourceUrl: "https://live.wellihillipark.com/wellihillipark/_definst_/cam07.stream/playlist.m3u8",
        externalPageUrl: "https://m.wellihillipark.com/customer/webcam",
        displayOrder: 6,
      },
    ],
  },
  {
    code: "PHOENIX",
    name: "휘닉스파크",
    regionName: "강원 평창",
    displayOrder: 2,
    cameras: [
      {
        code: "CAM_05",
        name: "펭귄 슬로프 (실시간 LIVE)",
        sourceType: "HLS",
        sourceUrl: "https://streaming.phoenixhnr.co.kr/hls/bc_01.m3u8",
        externalPageUrl: "https://phoenixhnr.co.kr/page/pyeongchang/guide/operation/sketchMovie",
        displayOrder: 1,
      },
      {
        code: "CAM_01",
        name: "호크 / 스패로우",
        sourceType: "HLS",
        sourceUrl: "https://streaming.phoenixhnr.co.kr/hls/yh_02_02.m3u8",
        externalPageUrl: "https://phoenixhnr.co.kr/page/pyeongchang/guide/operation/sketchMovie",
        displayOrder: 2,
      },
      {
        code: "CAM_02",
        name: "도도 슬로프",
        sourceType: "HLS",
        sourceUrl: "https://streaming.phoenixhnr.co.kr/hls/sp_01_01.m3u8",
        externalPageUrl: "https://phoenixhnr.co.kr/page/pyeongchang/guide/operation/sketchMovie",
        displayOrder: 3,
      },
      {
        code: "CAM_03",
        name: "불새마루",
        sourceType: "HLS",
        sourceUrl: "https://streaming.phoenixhnr.co.kr/hls/ht_01_01.m3u8",
        externalPageUrl: "https://phoenixhnr.co.kr/page/pyeongchang/guide/operation/sketchMovie",
        displayOrder: 4,
      },
      {
        code: "CAM_04",
        name: "베이스 광장",
        sourceType: "HLS",
        sourceUrl: "https://streaming.phoenixhnr.co.kr/hls/bc_02_01.m3u8",
        externalPageUrl: "https://phoenixhnr.co.kr/page/pyeongchang/guide/operation/sketchMovie",
        displayOrder: 5,
      },
      {
        code: "CAM_06",
        name: "스노우 빌리지",
        sourceType: "HLS",
        sourceUrl: "https://streaming.phoenixhnr.co.kr/hls/yh_01_01.m3u8",
        externalPageUrl: "https://phoenixhnr.co.kr/page/pyeongchang/guide/operation/sketchMovie",
        displayOrder: 6,
      },
      {
        code: "CAM_07",
        name: "몽블랑 정상",
        sourceType: "HLS",
        sourceUrl: "https://streaming.phoenixhnr.co.kr/hls/mb_03_02.m3u8",
        externalPageUrl: "https://phoenixhnr.co.kr/page/pyeongchang/guide/operation/sketchMovie",
        displayOrder: 7,
      },
    ],
  },
  {
    code: "YONGPYONG",
    name: "모나용평",
    regionName: "강원 평창",
    displayOrder: 3,
    cameras: [
      {
        code: "CAM_01",
        name: "발왕산 氣 스카이워크",
        sourceType: "HLS",
        sourceUrl: "https://live.yongpyong.co.kr/cam01/index.m3u8",
        externalPageUrl: "https://www.yongpyong.co.kr/kor/guide/realTimeNews/ypResortWebcam.do",
        displayOrder: 1,
      },
      {
        code: "CAM_02",
        name: "발왕산 천년주목숲길",
        sourceType: "HLS",
        sourceUrl: "https://live.yongpyong.co.kr/cam02/index.m3u8",
        externalPageUrl: "https://www.yongpyong.co.kr/kor/guide/realTimeNews/ypResortWebcam.do",
        displayOrder: 2,
      },
      {
        code: "CAM_03",
        name: "옐로우 슬로프",
        sourceType: "HLS",
        sourceUrl: "https://live.yongpyong.co.kr/cam11/index.m3u8",
        externalPageUrl: "https://www.yongpyong.co.kr/kor/guide/realTimeNews/ypResortWebcam.do",
        displayOrder: 3,
      },
      {
        code: "CAM_04",
        name: "베이스 전경 / 레드 슬로프",
        sourceType: "HLS",
        sourceUrl: "https://live.yongpyong.co.kr/cam08/index.m3u8",
        externalPageUrl: "https://www.yongpyong.co.kr/kor/guide/realTimeNews/ypResortWebcam.do",
        displayOrder: 4,
      },
      {
        code: "CAM_05",
        name: "모나용평 진입로",
        sourceType: "HLS",
        sourceUrl: "https://live.yongpyong.co.kr/cam05/index.m3u8",
        externalPageUrl: "https://www.yongpyong.co.kr/kor/guide/realTimeNews/ypResortWebcam.do",
        displayOrder: 5,
      },
    ],
  },
  {
    code: "JISAN",
    name: "지산리조트",
    regionName: "경기 이천",
    displayOrder: 4,
    cameras: [
      {
        code: "CAM_01",
        name: "레몬 탑승장",
        sourceType: "HLS",
        sourceUrl: "https://ant.livecity.co.kr:5443/jisancam/streams/jisan1.m3u8",
        externalPageUrl: "https://www.jisanresort.co.kr/m/ski/slopes/webcam.asp",
        displayOrder: 1,
      },
      {
        code: "CAM_02",
        name: "오렌지 / 뉴오렌지 탑승장",
        sourceType: "HLS",
        sourceUrl: "https://ant.livecity.co.kr:5443/jisancam/streams/jisan2.m3u8",
        externalPageUrl: "https://www.jisanresort.co.kr/m/ski/slopes/webcam.asp",
        displayOrder: 2,
      },
      {
        code: "CAM_03",
        name: "5번 / 6번 슬로프",
        sourceType: "HLS",
        sourceUrl: "https://ant.livecity.co.kr:5443/jisancam/streams/jisan3.m3u8",
        externalPageUrl: "https://www.jisanresort.co.kr/m/ski/slopes/webcam.asp",
        displayOrder: 3,
      },
      {
        code: "CAM_04",
        name: "블루 탑승장",
        sourceType: "HLS",
        sourceUrl: "https://ant.livecity.co.kr:5443/jisancam/streams/jisan4.m3u8",
        externalPageUrl: "https://www.jisanresort.co.kr/m/ski/slopes/webcam.asp",
        displayOrder: 4,
      },
      {
        code: "CAM_05",
        name: "실버 탑승장",
        sourceType: "HLS",
        sourceUrl: "https://ant.livecity.co.kr:5443/jisancam/streams/jisan5.m3u8",
        externalPageUrl: "https://www.jisanresort.co.kr/m/ski/slopes/webcam.asp",
        displayOrder: 5,
      },
    ],
  },
  {
    code: "OAK_VALLEY",
    name: "오크밸리",
    regionName: "강원 원주",
    displayOrder: 5,
    cameras: [
      {
        code: "CAM_01",
        name: "베이스",
        sourceType: "HLS",
        sourceUrl: "https://cctv-oak9.ktcdn.co.kr/cctv/ch2.stream/chunklist.m3u8",
        externalPageUrl: "https://app.oakvalley.co.kr/mobileapp/reserve/ski/webcam.do",
        displayOrder: 1,
      },
      {
        code: "CAM_02",
        name: "I 슬로프",
        sourceType: "HLS",
        sourceUrl: "https://cctv-oak9.ktcdn.co.kr/cctv/ch9.stream/chunklist.m3u8",
        externalPageUrl: "https://app.oakvalley.co.kr/mobileapp/reserve/ski/webcam.do",
        displayOrder: 2,
      },
      {
        code: "CAM_03",
        name: "G 슬로프 하단",
        sourceType: "HLS",
        sourceUrl: "https://cctv-oak9.ktcdn.co.kr/cctv/ch7.stream/chunklist.m3u8",
        externalPageUrl: "https://app.oakvalley.co.kr/mobileapp/reserve/ski/webcam.do",
        displayOrder: 3,
      },
      {
        code: "CAM_04",
        name: "F 슬로프 상단",
        sourceType: "HLS",
        sourceUrl: "https://cctv-oak9.ktcdn.co.kr/cctv/ch6.stream/chunklist.m3u8",
        externalPageUrl: "https://app.oakvalley.co.kr/mobileapp/reserve/ski/webcam.do",
        displayOrder: 4,
      },
      {
        code: "CAM_05",
        name: "플라워 휴게소",
        sourceType: "HLS",
        sourceUrl: "https://cctv-oak9.ktcdn.co.kr/cctv/ch5.stream/chunklist.m3u8",
        externalPageUrl: "https://app.oakvalley.co.kr/mobileapp/reserve/ski/webcam.do",
        displayOrder: 5,
      },
    ],
  },
  {
    code: "ELYSIAN",
    name: "엘리시안 강촌",
    regionName: "강원 춘천",
    displayOrder: 6,
    cameras: [
      {
        code: "CAM_01",
        name: "슬로프 실시간 라이브캠",
        sourceType: "YOUTUBE",
        sourceUrl: "https://www.youtube.com/embed/O6_8VBu4FSA",
        externalPageUrl: "https://www.youtube.com/@11-lf8zw/streams",
        displayOrder: 1,
      },
    ],
  },
  {
    code: "ALPENSIA",
    name: "알펜시아리조트",
    regionName: "강원 평창",
    displayOrder: 7,
    cameras: [
      {
        code: "CAM_01",
        name: "알펜시아 스키장 실시간 캠",
        sourceType: "YOUTUBE",
        sourceUrl: "https://www.youtube.com/embed/I3azd8f2HhM",
        externalPageUrl: "https://www.alpensia.com/guide/web-cam.do",
        displayOrder: 1,
      },
    ],
  },
  {
    code: "EDEN_VALLEY",
    name: "에덴밸리리조트",
    regionName: "경남 양산",
    displayOrder: 8,
    cameras: [
      {
        code: "CAM_01",
        name: "베이직 슬로프",
        sourceType: "IFRAME",
        sourceUrl: "https://rtsp.me/embed/2kTsKt35/",
        externalPageUrl: "https://www.edenvalley.co.kr",
        displayOrder: 1,
      },
      {
        code: "CAM_02",
        name: "슬로프 광장",
        sourceType: "IFRAME",
        sourceUrl: "https://rtsp.me/embed/ry9aTdQh",
        externalPageUrl: "https://www.edenvalley.co.kr",
        displayOrder: 2,
      },
    ],
  },
  {
    code: "HIGH1",
    name: "하이원리조트",
    regionName: "강원 정선",
    displayOrder: 9,
    cameras: [
      {
        code: "CAM_01",
        name: "하이원탑 (제우스1 입구)",
        sourceType: "HLS",
        sourceUrl: "/api/high1-stream/1/playlist.m3u8",
        externalPageUrl: "https://www.high1.com/webcam/pop_webcam.do?ch=1",
        displayOrder: 1,
      },
      {
        code: "CAM_02",
        name: "하이원탑 (헤라2 입구)",
        sourceType: "HLS",
        sourceUrl: "/api/high1-stream/2/playlist.m3u8",
        externalPageUrl: "https://www.high1.com/webcam/pop_webcam.do?ch=2",
        displayOrder: 2,
      },
      {
        code: "CAM_03",
        name: "마운틴허브 (스노우월드 입구)",
        sourceType: "HLS",
        sourceUrl: "/api/high1-stream/4/playlist.m3u8",
        externalPageUrl: "https://www.high1.com/webcam/pop_webcam.do?ch=4",
        displayOrder: 3,
      },
      {
        code: "CAM_04",
        name: "마운틴허브 (아폴로3 입구)",
        sourceType: "HLS",
        sourceUrl: "/api/high1-stream/5/playlist.m3u8",
        externalPageUrl: "https://www.high1.com/webcam/pop_webcam.do?ch=5",
        displayOrder: 4,
      },
      {
        code: "CAM_05",
        name: "마운틴허브 (아테나2 입구)",
        sourceType: "HLS",
        sourceUrl: "/api/high1-stream/6/playlist.m3u8",
        externalPageUrl: "https://www.high1.com/webcam/pop_webcam.do?ch=6",
        displayOrder: 5,
      },
      {
        code: "CAM_06",
        name: "마운틴 베이스 (아테나 리프트)",
        sourceType: "HLS",
        sourceUrl: "/api/high1-stream/7/playlist.m3u8",
        externalPageUrl: "https://www.high1.com/webcam/pop_webcam.do?ch=7",
        displayOrder: 6,
      },
      {
        code: "CAM_07",
        name: "아테나2 하단",
        sourceType: "HLS",
        sourceUrl: "/api/high1-stream/8/playlist.m3u8",
        externalPageUrl: "https://www.high1.com/webcam/pop_webcam.do?ch=8",
        displayOrder: 7,
      },
      {
        code: "CAM_08",
        name: "밸리허브 (헤라 리프트 입구)",
        sourceType: "HLS",
        sourceUrl: "/api/high1-stream/11/playlist.m3u8",
        externalPageUrl: "https://www.high1.com/webcam/pop_webcam.do?ch=11",
        displayOrder: 8,
      },
      {
        code: "CAM_09",
        name: "밸리허브 (아폴로3 합류)",
        sourceType: "HLS",
        sourceUrl: "/api/high1-stream/12/playlist.m3u8",
        externalPageUrl: "https://www.high1.com/webcam/pop_webcam.do?ch=12",
        displayOrder: 9,
      },
      {
        code: "CAM_10",
        name: "밸리허브 (제우스3)",
        sourceType: "HLS",
        sourceUrl: "/api/high1-stream/13/playlist.m3u8",
        externalPageUrl: "https://www.high1.com/webcam/pop_webcam.do?ch=13",
        displayOrder: 10,
      },
      {
        code: "CAM_11",
        name: "제우스3 중단",
        sourceType: "HLS",
        sourceUrl: "/api/high1-stream/14/playlist.m3u8",
        externalPageUrl: "https://www.high1.com/webcam/pop_webcam.do?ch=14",
        displayOrder: 11,
      },
      {
        code: "CAM_12",
        name: "아폴로4 중단",
        sourceType: "HLS",
        sourceUrl: "/api/high1-stream/15/playlist.m3u8",
        externalPageUrl: "https://www.high1.com/webcam/pop_webcam.do?ch=15",
        displayOrder: 12,
      },
      {
        code: "CAM_13",
        name: "아폴로 베이스",
        sourceType: "HLS",
        sourceUrl: "/api/high1-stream/16/playlist.m3u8",
        externalPageUrl: "https://www.high1.com/webcam/pop_webcam.do?ch=16",
        displayOrder: 13,
      },
      {
        code: "CAM_14",
        name: "제우스3 하단",
        sourceType: "HLS",
        sourceUrl: "/api/high1-stream/17/playlist.m3u8",
        externalPageUrl: "https://www.high1.com/webcam/pop_webcam.do?ch=17",
        displayOrder: 14,
      },
      {
        code: "CAM_15",
        name: "밸리 베이스",
        sourceType: "HLS",
        sourceUrl: "/api/high1-stream/18/playlist.m3u8",
        externalPageUrl: "https://www.high1.com/webcam/pop_webcam.do?ch=18",
        displayOrder: 15,
      },
    ],
  },
  {
    code: "VIVALDI",
    name: "비발디파크",
    regionName: "강원 홍천",
    displayOrder: 10,
    cameras: [
      {
        code: "CAM_01",
        name: "슬로프 전경",
        sourceType: "IFRAME",
        sourceUrl: "/vivaldi.html?channel=8&serial=TW0014A15451&autoplay=true",
        externalPageUrl: "https://mice.sonohotelsresorts.com/daemyung.vp.utill.09_02_02_01.ds/dmparse.dm?areaType=S",
        displayOrder: 1,
      },
      {
        code: "CAM_02",
        name: "발라드 상단",
        sourceType: "IFRAME",
        sourceUrl: "/vivaldi.html?channel=11&serial=TD0314A17496&autoplay=true",
        externalPageUrl: "https://mice.sonohotelsresorts.com/daemyung.vp.utill.09_02_02_01.ds/dmparse.dm?areaType=S",
        displayOrder: 2,
      },
      {
        code: "CAM_03",
        name: "발라드 하단",
        sourceType: "IFRAME",
        sourceUrl: "/vivaldi.html?channel=2&serial=TW0014A15451&autoplay=true",
        externalPageUrl: "https://mice.sonohotelsresorts.com/daemyung.vp.utill.09_02_02_01.ds/dmparse.dm?areaType=S",
        displayOrder: 3,
      },
      {
        code: "CAM_04",
        name: "재즈 상단",
        sourceType: "IFRAME",
        sourceUrl: "/vivaldi.html?channel=4&serial=XU0121A37907&autoplay=true",
        externalPageUrl: "https://mice.sonohotelsresorts.com/daemyung.vp.utill.09_02_02_01.ds/dmparse.dm?areaType=S",
        displayOrder: 4,
      },
      {
        code: "CAM_05",
        name: "재즈 하단",
        sourceType: "IFRAME",
        sourceUrl: "/vivaldi.html?channel=1&serial=TW0014A15451&autoplay=true",
        externalPageUrl: "https://mice.sonohotelsresorts.com/daemyung.vp.utill.09_02_02_01.ds/dmparse.dm?areaType=S",
        displayOrder: 5,
      },
      {
        code: "CAM_06",
        name: "테크노 상단",
        sourceType: "IFRAME",
        sourceUrl: "/vivaldi.html?channel=2&serial=XU0121A37904&autoplay=true",
        externalPageUrl: "https://mice.sonohotelsresorts.com/daemyung.vp.utill.09_02_02_01.ds/dmparse.dm?areaType=S",
        displayOrder: 6,
      },
      {
        code: "CAM_07",
        name: "테크노 하단",
        sourceType: "IFRAME",
        sourceUrl: "/vivaldi.html?channel=5&serial=XU0121A37904&autoplay=true",
        externalPageUrl: "https://mice.sonohotelsresorts.com/daemyung.vp.utill.09_02_02_01.ds/dmparse.dm?areaType=S",
        displayOrder: 7,
      },
      {
        code: "CAM_08",
        name: "블루스",
        sourceType: "IFRAME",
        sourceUrl: "/vivaldi.html?channel=4&serial=TW0014A15451&autoplay=true",
        externalPageUrl: "https://mice.sonohotelsresorts.com/daemyung.vp.utill.09_02_02_01.ds/dmparse.dm?areaType=S",
        displayOrder: 8,
      },
      {
        code: "CAM_09",
        name: "클래식",
        sourceType: "IFRAME",
        sourceUrl: "/vivaldi.html?channel=10&serial=TW0014A15451&autoplay=true",
        externalPageUrl: "https://mice.sonohotelsresorts.com/daemyung.vp.utill.09_02_02_01.ds/dmparse.dm?areaType=S",
        displayOrder: 9,
      },
      {
        code: "CAM_10",
        name: "레게",
        sourceType: "IFRAME",
        sourceUrl: "/vivaldi.html?channel=10&serial=TD0314A17496&autoplay=true",
        externalPageUrl: "https://mice.sonohotelsresorts.com/daemyung.vp.utill.09_02_02_01.ds/dmparse.dm?areaType=S",
        displayOrder: 10,
      },
      {
        code: "CAM_11",
        name: "펑키 상단",
        sourceType: "IFRAME",
        sourceUrl: "/vivaldi.html?channel=5&serial=TW0014A15451&autoplay=true",
        externalPageUrl: "https://mice.sonohotelsresorts.com/daemyung.vp.utill.09_02_02_01.ds/dmparse.dm?areaType=S",
        displayOrder: 11,
      },
      {
        code: "CAM_12",
        name: "펑키 하단",
        sourceType: "IFRAME",
        sourceUrl: "/vivaldi.html?channel=8&serial=XU0121A37904&autoplay=true",
        externalPageUrl: "https://mice.sonohotelsresorts.com/daemyung.vp.utill.09_02_02_01.ds/dmparse.dm?areaType=S",
        displayOrder: 12,
      },
      {
        code: "CAM_13",
        name: "힙합",
        sourceType: "IFRAME",
        sourceUrl: "/vivaldi.html?channel=6&serial=TW0014A15451&autoplay=true",
        externalPageUrl: "https://mice.sonohotelsresorts.com/daemyung.vp.utill.09_02_02_01.ds/dmparse.dm?areaType=S",
        displayOrder: 13,
      },
      {
        code: "CAM_14",
        name: "스키월드 정상",
        sourceType: "IFRAME",
        sourceUrl: "/vivaldi.html?channel=9&serial=TW0014A15451&autoplay=true",
        externalPageUrl: "https://mice.sonohotelsresorts.com/daemyung.vp.utill.09_02_02_01.ds/dmparse.dm?areaType=S",
        displayOrder: 14,
      },
      {
        code: "CAM_15",
        name: "스노위랜드1",
        sourceType: "IFRAME",
        sourceUrl: "/vivaldi.html?channel=16&serial=TD0314A17496&autoplay=true",
        externalPageUrl: "https://mice.sonohotelsresorts.com/daemyung.vp.utill.09_02_02_01.ds/dmparse.dm?areaType=S",
        displayOrder: 15,
      },
      {
        code: "CAM_16",
        name: "스노위랜드2",
        sourceType: "IFRAME",
        sourceUrl: "/vivaldi.html?channel=12&serial=TD0314A17496&autoplay=true",
        externalPageUrl: "https://mice.sonohotelsresorts.com/daemyung.vp.utill.09_02_02_01.ds/dmparse.dm?areaType=S",
        displayOrder: 16,
      },
    ],
  },
  {
    code: "KONJIAM",
    name: "곤지암리조트",
    regionName: "경기 광주",
    displayOrder: 11,
    cameras: [
      {
        code: "CAM_01",
        name: "정상 휴게소",
        sourceType: "HLS",
        sourceUrl: "https://video.fpkorea.com/konjiam/cam01.stream/playlist.m3u8",
        externalPageUrl: "https://m.konjiamresort.co.kr/ski/skiLveCam.dev",
        displayOrder: 1,
      },
      {
        code: "CAM_02",
        name: "정상부 슬로프 (씽큐, 그램)",
        sourceType: "HLS",
        sourceUrl: "https://video.fpkorea.com/konjiam/cam02.stream/playlist.m3u8",
        externalPageUrl: "https://m.konjiamresort.co.kr/ski/skiLveCam.dev",
        displayOrder: 2,
      },
      {
        code: "CAM_03",
        name: "초중급 베이스 (휘센)",
        sourceType: "HLS",
        sourceUrl: "https://video.fpkorea.com/konjiam/cam03.stream/playlist.m3u8",
        externalPageUrl: "https://m.konjiamresort.co.kr/ski/skiLveCam.dev",
        displayOrder: 3,
      },
      {
        code: "CAM_04",
        name: "중상급 베이스 (와이낫, CNP)",
        sourceType: "HLS",
        sourceUrl: "https://video.fpkorea.com/konjiam/cam04.stream/playlist.m3u8",
        externalPageUrl: "https://m.konjiamresort.co.kr/ski/skiLveCam.dev",
        displayOrder: 4,
      },
      {
        code: "CAM_05",
        name: "중간 슬로프 (와이낫 상단)",
        sourceType: "HLS",
        sourceUrl: "https://video.fpkorea.com/konjiam/cam05.stream/playlist.m3u8",
        externalPageUrl: "https://m.konjiamresort.co.kr/ski/skiLveCam.dev",
        displayOrder: 5,
      },
    ],
  },
  {
    code: "MUJU",
    name: "무주덕유산리조트",
    regionName: "전북 무주",
    displayOrder: 12,
    cameras: [
      {
        code: "CAM_01",
        name: "만선하우스",
        sourceType: "HLS",
        sourceUrl: "/api/muju-stream/01/playlist.m3u8",
        externalPageUrl: "http://www.mdysresort.com/guide/webcam_popup_jh.asp?cam_num=01",
        displayOrder: 1,
      },
      {
        code: "CAM_02",
        name: "만선봉 정상",
        sourceType: "HLS",
        sourceUrl: "/api/muju-stream/02/playlist.m3u8",
        externalPageUrl: "http://www.mdysresort.com/guide/webcam_popup_jh.asp?cam_num=02",
        displayOrder: 2,
      },
      {
        code: "CAM_03",
        name: "하이디하우스",
        sourceType: "HLS",
        sourceUrl: "/api/muju-stream/03/playlist.m3u8",
        externalPageUrl: "http://www.mdysresort.com/guide/webcam_popup_jh.asp?cam_num=03",
        displayOrder: 3,
      },
      {
        code: "CAM_04",
        name: "서역기행, 썬다운",
        sourceType: "HLS",
        sourceUrl: "/api/muju-stream/04/playlist.m3u8",
        externalPageUrl: "http://www.mdysresort.com/guide/webcam_popup_jh.asp?cam_num=04",
        displayOrder: 4,
      },
      {
        code: "CAM_05",
        name: "설천하우스",
        sourceType: "HLS",
        sourceUrl: "/api/muju-stream/05/playlist.m3u8",
        externalPageUrl: "http://www.mdysresort.com/guide/webcam_popup_jh.asp?cam_num=05",
        displayOrder: 5,
      },
      {
        code: "CAM_06",
        name: "설천 상단 슬로프",
        sourceType: "HLS",
        sourceUrl: "/api/muju-stream/06/playlist.m3u8",
        externalPageUrl: "http://www.mdysresort.com/guide/webcam_popup_jh.asp?cam_num=06",
        displayOrder: 6,
      },
      {
        code: "CAM_07",
        name: "설천봉 정상",
        sourceType: "HLS",
        sourceUrl: "/api/muju-stream/07/playlist.m3u8",
        externalPageUrl: "http://www.mdysresort.com/guide/webcam_popup_jh.asp?cam_num=07",
        displayOrder: 7,
      },
      {
        code: "CAM_08",
        name: "모차르트, 미뉴에트",
        sourceType: "HLS",
        sourceUrl: "/api/muju-stream/08/playlist.m3u8",
        externalPageUrl: "http://www.mdysresort.com/guide/webcam_popup_jh.asp?cam_num=08",
        displayOrder: 8,
      },
      {
        code: "CAM_09",
        name: "폴카",
        sourceType: "HLS",
        sourceUrl: "/api/muju-stream/09/playlist.m3u8",
        externalPageUrl: "http://www.mdysresort.com/guide/webcam_popup_jh.asp?cam_num=09",
        displayOrder: 9,
      },
      {
        code: "CAM_10",
        name: "실크로드, 미뉴에트 하단",
        sourceType: "HLS",
        sourceUrl: "/api/muju-stream/10/playlist.m3u8",
        externalPageUrl: "http://www.mdysresort.com/guide/webcam_popup_jh.asp?cam_num=10",
        displayOrder: 10,
      },
      {
        code: "CAM_11",
        name: "커넥션",
        sourceType: "HLS",
        sourceUrl: "/api/muju-stream/11/playlist.m3u8",
        externalPageUrl: "http://www.mdysresort.com/guide/webcam_popup_jh.asp?cam_num=11",
        displayOrder: 11,
      },
    ],
  },
  {
    code: "O2_RESORT",
    name: "오투리조트",
    regionName: "강원 태백",
    displayOrder: 13,
    cameras: [
      {
        code: "CAM_01",
        name: "스키하우스",
        sourceType: "HLS",
        sourceUrl: "/api/o2-stream/cam0.m3u8",
        externalPageUrl: "https://www.o2resort.com/ski/webcam.asp",
        displayOrder: 1,
      },
      {
        code: "CAM_02",
        name: "오렌지",
        sourceType: "HLS",
        sourceUrl: "/api/o2-stream/cam1.m3u8",
        externalPageUrl: "https://www.o2resort.com/ski/webcam.asp",
        displayOrder: 2,
      },
      {
        code: "CAM_03",
        name: "버금마루",
        sourceType: "HLS",
        sourceUrl: "/api/o2-stream/cam2.m3u8",
        externalPageUrl: "https://www.o2resort.com/ski/webcam.asp",
        displayOrder: 3,
      },
      {
        code: "CAM_04",
        name: "으뜸마루",
        sourceType: "HLS",
        sourceUrl: "/api/o2-stream/cam3.m3u8",
        externalPageUrl: "https://www.o2resort.com/ski/webcam.asp",
        displayOrder: 4,
      },
      {
        code: "CAM_05",
        name: "글로리2 상단",
        sourceType: "HLS",
        sourceUrl: "/api/o2-stream/cam20.m3u8",
        externalPageUrl: "https://www.o2resort.com/ski/webcam.asp",
        displayOrder: 5,
      },
      {
        code: "CAM_06",
        name: "글로리3 상단",
        sourceType: "HLS",
        sourceUrl: "/api/o2-stream/cam21.m3u8",
        externalPageUrl: "https://www.o2resort.com/ski/webcam.asp",
        displayOrder: 6,
      },
      {
        code: "CAM_07",
        name: "드림2 상단",
        sourceType: "HLS",
        sourceUrl: "/api/o2-stream/cam22.m3u8",
        externalPageUrl: "https://www.o2resort.com/ski/webcam.asp",
        displayOrder: 7,
      },
      {
        code: "CAM_08",
        name: "글로리3",
        sourceType: "HLS",
        sourceUrl: "/api/o2-stream/cam23.m3u8",
        externalPageUrl: "https://www.o2resort.com/ski/webcam.asp",
        displayOrder: 8,
      },
    ],
  },
];
